CREATE
	OR 
REPLACE
	VIEW v_dat_shipments AS 
SELECT
	`p`.`parentID`                                      AS `parentID`
	,`p`.`L1`                                             AS `l1`
	,`p`.`L2`                                             AS `l2`
	,`p`.`L3`                                             AS `l3`
	,`p`.`L4`                                             AS `l4`
	,`p`.`L5`                                             AS `l5`
	,`g`.`Region_Name`                                    AS `Region_Name`
	,`g`.`Sub_region_Name`                                AS `Sub_region_Name`
	,`g`.`Intermediate_Region_Name`                       AS `Intermediate_Region_Name`
	,`s`.`Shipment_ID`                                    AS `Shipment_ID`
	,`s`.`Country_ISO_Code`                               AS `Country_ISO_Code`
	,`s`.`Country_Name`                                   AS `Country_Name`
	,`s`.`Recipient_DUNS`                                 AS `Recipient_DUNS`
	,`s`.`Recipient_DUNS_4`                               AS `Recipient_DUNS_4`
	,`s`.`Recipient_Address_Descriptor`                   AS `Recipient_Address_Descriptor`
	,`s`.`Recipient_Address_1`                            AS `Recipient_Address_1`
	,`s`.`Recipient_Address_2`                            AS `Recipient_Address_2`
	,`s`.`Recipient_Address_3`                            AS `Recipient_Address_3`
	,`s`.`Recipient_Address_4`                            AS `Recipient_Address_4`
	,`s`.`Recipient_Address_5`                            AS `Recipient_Address_5`
	,`s`.`Recipient_City`                                 AS `Recipient_City`
	,`s`.`Recipient_County`                               AS `Recipient_County`
	,`s`.`Recipient_State`                                AS `Recipient_State`
	,`s`.`Recipient_Country`                              AS `Recipient_Country`
	,`s`.`Recipient_Zip`                                  AS `Recipient_Zip`
	,`s`.`Supplier_ID`                                    AS `Supplier_ID`
	,`s`.`Supplier_Description`                           AS `Supplier_Description`
	,`s`.`Supplier_DUNS`                                  AS `Supplier_DUNS`
	,`s`.`Supplier_DUNS_4`                                AS `Supplier_DUNS_4`
	,`s`.`Supplier_Address_Descriptor`                    AS `Supplier_Address_Descriptor`
	,`s`.`Supplier_Address_1`                             AS `Supplier_Address_1`
	,`s`.`Supplier_Address_2`                             AS `Supplier_Address_2`
	,`s`.`Supplier_Address_3`                             AS `Supplier_Address_3`
	,`s`.`Supplier_Address_4`                             AS `Supplier_Address_4`
	,`s`.`Supplier_Address_5`                             AS `Supplier_Address_5`
	,`s`.`Supplier_City`                                  AS `Supplier_City`
	,`s`.`Supplier_County`                                AS `Supplier_County`
	,`s`.`Supplier_State`                                 AS `Supplier_State`
	,`s`.`Supplier_Country`                               AS `Supplier_Country`
	,`s`.`Supplier_Zip`                                   AS `Supplier_Zip`
	,`s`.`Shipment_Creation_Date`                         AS `Shipment_Creation_Date`
	,`s`.`Shipment_Creator_Code`                          AS `Shipment_Creator_Code`
	,`s`.`Shipment_Status`                                AS `Shipment_Status`
	,`s`.`Estimated_Ship_Date`                            AS `Estimated_Ship_Date`
	,`s`.`Estimated_Delivery_Date`                        AS `Estimated_Delivery_Date`
	,`s`.`Final_Site_ETA`                                 AS `Final_Site_ETA`
	,`s`.`Last_Known_Milestone`                           AS `Last_Known_Milestone`
	,`s`.`Last_Known_Milestone_Arrival`                   AS `Last_Known_Milestone_Arrival`
	,`s`.`Last_Known_Milestone_Departure`                 AS `Last_Known_Milestone_Departure`
	,`s`.`Carrier`                                        AS `Carrier`
	,`s`.`Shipment_Mode`                                  AS `Shipment_Mode`
	,`s`.`Waybill_num`                                    AS `Waybill_num`
	,`s`.`Shipment_Delivery_BOL_num`                      AS `Shipment_Delivery_BOL_num`
	,`s`.`Packing_Slip_num`                               AS `Packing_Slip_num`
	,`s`.`Carrier_Reference_num`                          AS `Carrier_Reference_num`
	,`s`.`Shipper_Reference_num`                          AS `Shipper_Reference_num`
	,`s`.`Ship_To_Type_Site_Hub`                          AS `Ship_To_Type_Site_Hub`
	,`s`.`Country_Of_Origin`                              AS `Country_Of_Origin`
	,`s`.`Number_Of_Packages`                             AS `Number_Of_Packages`
	,`s`.`License_Plate_Number`                           AS `License_Plate_Number`
	,`s`.`Importer_Of_num`                                AS `Importer_Of_num`
	,`s`.`Consignee_num`                                  AS `Consignee_num`
	,`s`.`Foreign_Port_Of_Unlading`                       AS `Foreign_Port_Of_Unlading`
	,`s`.`Place_Of_Delivery`                              AS `Place_Of_Delivery`
	,`s`.`Supply_Plan_Bucket`                             AS `Supply_Plan_Bucket`
	,`s`.`Ship_to_Party_Name`                             AS `Ship_to_Party_Name`
	,`s`.`Ship_to_Party_DUNS`                             AS `Ship_to_Party_DUNS`
	,`s`.`Ship_To_Address_Descriptor`                     AS `Ship_To_Address_Descriptor`
	,`s`.`Ship_To_Address_1`                              AS `Ship_To_Address_1`
	,`s`.`Ship_To_Address_2`                              AS `Ship_To_Address_2`
	,`s`.`Ship_To_Address_3`                              AS `Ship_To_Address_3`
	,`s`.`Ship_To_Address_4`                              AS `Ship_To_Address_4`
	,`s`.`Ship_To_Address_5`                              AS `Ship_To_Address_5`
	,`s`.`Ship_To_City`                                   AS `Ship_To_City`
	,`s`.`Ship_To_County`                                 AS `Ship_To_County`
	,`s`.`Ship_To_State`                                  AS `Ship_To_State`
	,`s`.`Ship_To_Country`                                AS `Ship_To_Country`
	,`s`.`Ship_To_Zip`                                    AS `Ship_To_Zip`
	,`s`.`Supplier_Site`                                  AS `Supplier_Site`
	,`s`.`Ship_From_Address_Descriptor`                   AS `Ship_From_Address_Descriptor`
	,`s`.`Ship_From_Address_1`                            AS `Ship_From_Address_1`
	,`s`.`Ship_From_Address_2`                            AS `Ship_From_Address_2`
	,`s`.`Ship_From_Address_3`                            AS `Ship_From_Address_3`
	,`s`.`Ship_From_Address_4`                            AS `Ship_From_Address_4`
	,`s`.`Ship_From_Address_5`                            AS `Ship_From_Address_5`
	,`s`.`Ship_From_City`                                 AS `Ship_From_City`
	,`s`.`Ship_From_County`                               AS `Ship_From_County`
	,`s`.`Ship_From_State`                                AS `Ship_From_State`
	,`s`.`Ship_From_Country`                              AS `Ship_From_Country`
	,`s`.`Ship_From_Zip`                                  AS `Ship_From_Zip`
	,`s`.`Funder`                                         AS `Funder`
	,`s`.`Bill_To_Address_Descriptor`                     AS `Bill_To_Address_Descriptor`
	,`s`.`Bill_To_Address_1`                              AS `Bill_To_Address_1`
	,`s`.`Bill_To_Address_2`                              AS `Bill_To_Address_2`
	,`s`.`Bill_To_Address_3`                              AS `Bill_To_Address_3`
	,`s`.`Bill_To_Address_4`                              AS `Bill_To_Address_4`
	,`s`.`Bill_To_Address_5`                              AS `Bill_To_Address_5`
	,`s`.`Bill_To_City`                                   AS `Bill_To_City`
	,`s`.`Bill_To_County`                                 AS `Bill_To_County`
	,`s`.`Bill_To_State`                                  AS `Bill_To_State`
	,`s`.`Bill_To_Country`                                AS `Bill_To_Country`
	,`s`.`Bill_To_Zip`                                    AS `Bill_To_Zip`
	,`s`.`Booking_Party_Name`                             AS `Booking_Party_Name`
	,`s`.`Booking_Party_DUNS`                             AS `Booking_Party_DUNS`
	,`s`.`Booking_Party_Address_Descriptor`               AS `Booking_Party_Address_Descriptor`
	,`s`.`Booking_Party_Address_1`                        AS `Booking_Party_Address_1`
	,`s`.`Booking_Party_Address_2`                        AS `Booking_Party_Address_2`
	,`s`.`Booking_Party_Address_3`                        AS `Booking_Party_Address_3`
	,`s`.`Booking_Party_Address_4`                        AS `Booking_Party_Address_4`
	,`s`.`Booking_Party_Address_5`                        AS `Booking_Party_Address_5`
	,`s`.`Booking_Party_City`                             AS `Booking_Party_City`
	,`s`.`Booking_Party_County`                           AS `Booking_Party_County`
	,`s`.`Booking_Party_State`                            AS `Booking_Party_State`
	,`s`.`Booking_Party_Country`                          AS `Booking_Party_Country`
	,`s`.`Booking_Party_Zip`                              AS `Booking_Party_Zip`
	,`s`.`Category_Status`                                AS `Category_Status`
	,`s`.`Date_Type`                                      AS `Date_Type`
	,`s`.`Customer_Other`                                 AS `Customer_Other`
	,`s`.`Customer_Category`                              AS `Customer_Category`
	,`s`.`Program_Recipient_Description`                  AS `Program_Recipient_Description`
	,`s`.`Supply_Plan_Bucket_Description`                 AS `Supply_Plan_Bucket_Description`
	,`s`.`Transaction_ID`                                 AS `Transaction_ID`
	,`s`.`Internal_Field_Flow_Indicator`                  AS `Internal_Field_Flow_Indicator`
	,`s`.`Actual_Ship_Date`                               AS `Actual_Ship_Date`
	,`s`.`Shipment_Line_ID`                               AS `Shipment_Line_ID`
	,`s`.`Shipment_Line_Status`                           AS `Shipment_Line_Status`
	,`s`.`Action`                                         AS `Action`
	,`s`.`Product_Item_ID_Internal`                       AS `Product_Item_ID_Internal`
	,`s`.`Product_Description`                            AS `Product_Description`
	,`s`.`Supplier_Item_ID`                               AS `Supplier_Item_ID`
	,`s`.`Supplier_Item_Description`                      AS `Supplier_Item_Description`
	,`s`.`Procurer`                                       AS `Procurer`
	,`s`.`Shipped_Qty`                                    AS `Shipped_Qty`
	,`s`.`Base_UOM`                                       AS `Base_UOM`
	,`s`.`Freight_Cost`                                   AS `Freight_Cost`
	,`s`.`VAN_Internal_Item_ID`                           AS `VAN_Internal_Item_ID`     
	,`s`.`Packing_Slip_num_Line`                          AS `Packing_Slip_num_Line`
	,`s`.`Shipment_Line_Notes`                            AS `Shipment_Line_Notes`
	,`s`.`num_Of_Boxes`                                   AS `num_Of_Boxes`
	,`s`.`Weight`                                         AS `Weight`
	,`s`.`Commodity_HTS_6`                                AS `Commodity_HTS_6`
	,`s`.`Manufacturer_Description`                       AS `Manufacturer_Description`
	,`s`.`Manufacturer_ID`                                AS `Manufacturer_ID`          
	,`s`.`Manufacturer_Address_Descriptor`                AS `Manufacturer_Address_Descriptor`
	,`s`.`Manufacturer_Address_1`                         AS `Manufacturer_Address_1`
	,`s`.`Manufacturer_Address_2`                         AS `Manufacturer_Address_2`
	,`s`.`Manufacturer_Address_3`                         AS `Manufacturer_Address_3`
	,`s`.`Manufacturer_Address_4`                         AS `Manufacturer_Address_4`
	,`s`.`Manufacturer_Address_5`                         AS `Manufacturer_Address_5`
	,`s`.`Manufacturer_City`                              AS `Manufacturer_City`
	,`s`.`Manufacturer_County`                            AS `Manufacturer_County`
	,`s`.`Manufacturer_State`                             AS `Manufacturer_State`
	,`s`.`Manufacturer_Country`                           AS `Manufacturer_Country`
	,`s`.`Manufacturer_Zip`                               AS `Manufacturer_Zip`
	,`s`.`Container_Stuffing_Location_Name`               AS `Container_Stuffing_Location_Name`
	,`s`.`Container_Stuffing_Location_DUNS`               AS `Container_Stuffing_Location_DUNS`
	,`s`.`Container_Stuffing_Location_Address_Descriptor` AS `Container_Stuffing_Location_Address_Descriptor`
	,`s`.`Container_Stuffing_Location_Address_1`          AS `Container_Stuffing_Location_Address_1`
	,`s`.`Container_Stuffing_Location_Address_2`          AS `Container_Stuffing_Location_Address_2`
	,`s`.`Container_Stuffing_Location_Address_3`          AS `Container_Stuffing_Location_Address_3`
	,`s`.`Container_Stuffing_Location_Address_4`          AS `Container_Stuffing_Location_Address_4`
	,`s`.`Container_Stuffing_Location_Address_5`          AS `Container_Stuffing_Location_Address_5`
	,`s`.`Container_Stuffing_Location_City`               AS `Container_Stuffing_Location_City`
	,`s`.`Container_Stuffing_Location_County`             AS `Container_Stuffing_Location_County`
	,`s`.`Container_Stuffing_Location_State`              AS `Container_Stuffing_Location_State`
	,`s`.`Container_Stuffing_Location_Country`            AS `Container_Stuffing_Location_Country`
	,`s`.`Container_Stuffing_Location_Zip`                AS `Container_Stuffing_Location_Zip`
	,`s`.`Consolidator_Name`                              AS `Consolidator_Name`
	,`s`.`Consolidator_DUNS`                              AS `Consolidator_DUNS`
	,`s`.`Consolidator_Address_Descriptor`                AS `Consolidator_Address_Descriptor`
	,`s`.`Consolidator_Address_1`                         AS `Consolidator_Address_1`
	,`s`.`Consolidator_Address_2`                         AS `Consolidator_Address_2`
	,`s`.`Consolidator_Address_3`                         AS `Consolidator_Address_3`
	,`s`.`Consolidator_Address_4`                         AS `Consolidator_Address_4`
	,`s`.`Consolidator_Address_5`                         AS `Consolidator_Address_5`
	,`s`.`Consolidator_City`                              AS `Consolidator_City`
	,`s`.`Consolidator_County`                            AS `Consolidator_County`
	,`s`.`Consolidator_State`                             AS `Consolidator_State`
	,`s`.`Consolidator_Country`                           AS `Consolidator_Country`
	,`s`.`Consolidator_Zip`                               AS `Consolidator_Zip`
	,`s`.`Ref_Country_ISO_Code`                           AS `Ref_Country_ISO_Code`
	,`s`.`Ref_Supplier_ID`                                AS `Ref_Supplier_ID`
	,`s`.`Ref_Order_Type`                                 AS `Ref_Order_Type`
	,`s`.`Ref_Order_ID`                                   AS `Ref_Order_ID`
	,`s`.`Ref_Order_Line_ID`                              AS `Ref_Order_Line_ID`
	,`s`.`Ref_Order_Request_ID`                           AS `Ref_Order_Request_ID`
	,`s`.`Ref_Order_Promise_ID`                           AS `Ref_Order_Promise_ID`
	,`s`.`Procurer_Item_ID`                               AS `Procurer_Item_ID`
	,`s`.`Procurer_Item_Description`                      AS `Procurer_Item_Description`
	,`s`.`Batch_Lot_Info`                                 AS `Batch_Lot_Info`
	,`s`.`GTIN`                                           AS `GTIN`
	,`s`.`Related_Req_No`                                 AS `Related_Req_No`
	,`s`.`L5_Product`                                     AS `L5_Product`
	,`s`.`L3_Method`                                      AS `L3_Method`
	,`s`.`Source_UOM`                                     AS `Source_UOM`
	,`s`.`Supplier_Sales_Order_No`                        AS `Supplier_Sales_Order_No`
	,`s`.`UOM_Value_Factor`                               AS `UOM_Value_Factor`
	,`s`.`Ship_Leg_Status`                                AS `Ship_Leg_Status`
	,`s`.`UOM_Qty_Factor`                                 AS `UOM_Qty_Factor`
	,`s`.`Shipped_Source_Qty`                             AS `Shipped_Source_Qty`
	,`s`.`Goods_Available_Date`                           AS `Goods_Available_Date`
	,`s`.`Invoice_Date_Sent`                              AS `Invoice_Date_Sent`
	,`s`.`Ship_To_Recipient_ID`                           AS `Ship_To_Recipient_ID`
	,`s`.`Ship_To_Recipient_Desc`                         AS `Ship_To_Recipient_Desc`
	,`s`.`Ship_To_Recipient_Item_ID`                      AS `Ship_To_Recipient_Item_ID`
	,`s`.`Ship_To_Recipient_Item_Desc`                    AS `Ship_To_Recipient_Item_Desc`
	,`s`.`Drop_Shipment_Flag`                             AS `Drop_Shipment_Flag`
	,`s`.`Data_Provider`                                  AS `Data_Provider`
	,`s`.`Data_Visibility`                                AS `Data_Visibility`
	,`s`.`Customer_Type`                                  AS `Customer_Type`
	,`s`.`Program_Recipient_ID`                           AS `Program_Recipient_ID`
	,`s`.`Delivered_Date`                                 AS `Delivered_Date`
	,`s`.`Received_Date`                                  AS `Received_Date`
	,`s`.`Delivered_Qty`                                  AS `Delivered_Qty`
	,`s`.`Received_Qty`                                   AS `Received_Qty`
	-- ,`p`.`Reference_Price`                                AS `Estimated_Unit_Value_USD`
	-- ,(`s`.`Shipped_Qty` * `p`.`Reference_Price`)          AS `Estimated_Line_Value_USD`
	,s.Source_Order_No                                    AS `Source_Order_No`
FROM
	((`rhsc_gfpvan`.`dat_shipments` `s` 
		LEFT JOIN `rhsc_gfpvan`.`v_productitems` `p` 
		ON((`s`.`Product_Item_ID_Internal` = `p`.`parentID`))) 
		LEFT JOIN `rhsc_gfpvan`.`ref_georegions` `g` 
		ON((`g`.`ISO_2digit` = `s`.`Country_ISO_Code`))) 
WHERE
	(`p`.`parentID` IS NOT NULL)
    and p.productID not in ('981000','985001','991002','9911003','9913022','992003','993001','995000','995001')
